// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package store

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command int32

const (
	Command_Get     Command = 0
	Command_Put     Command = 1
	Command_Modify  Command = 2
	Command_Del     Command = 3
	Command_DellAll Command = 4
	Command_Keys    Command = 5
)

var Command_name = map[int32]string{
	0: "Get",
	1: "Put",
	2: "Modify",
	3: "Del",
	4: "DellAll",
	5: "Keys",
}
var Command_value = map[string]int32{
	"Get":     0,
	"Put":     1,
	"Modify":  2,
	"Del":     3,
	"DellAll": 4,
	"Keys":    5,
}

func (x Command) String() string {
	return proto.EnumName(Command_name, int32(x))
}
func (Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{0}
}

type Type int32

const (
	Type_Null   Type = 0
	Type_Int    Type = 1
	Type_Float  Type = 2
	Type_Bool   Type = 3
	Type_String Type = 4
	Type_blob   Type = 5
	Type_array  Type = 6
	Type_json   Type = 7
)

var Type_name = map[int32]string{
	0: "Null",
	1: "Int",
	2: "Float",
	3: "Bool",
	4: "String",
	5: "blob",
	6: "array",
	7: "json",
}
var Type_value = map[string]int32{
	"Null":   0,
	"Int":    1,
	"Float":  2,
	"Bool":   3,
	"String": 4,
	"blob":   5,
	"array":  6,
	"json":   7,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{1}
}

type Comp int32

const (
	Comp_Eq     Comp = 0
	Comp_Gt     Comp = 1
	Comp_Gte    Comp = 2
	Comp_Lt     Comp = 3
	Comp_Lte    Comp = 4
	Comp_Ne     Comp = 5
	Comp_Exists Comp = 6
)

var Comp_name = map[int32]string{
	0: "Eq",
	1: "Gt",
	2: "Gte",
	3: "Lt",
	4: "Lte",
	5: "Ne",
	6: "Exists",
}
var Comp_value = map[string]int32{
	"Eq":     0,
	"Gt":     1,
	"Gte":    2,
	"Lt":     3,
	"Lte":    4,
	"Ne":     5,
	"Exists": 6,
}

func (x Comp) String() string {
	return proto.EnumName(Comp_name, int32(x))
}
func (Comp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{2}
}

type Op int32

const (
	Op_Inc         Op = 0
	Op_Set         Op = 1
	Op_Unset       Op = 2
	Op_CurrentDate Op = 3
	Op_Min         Op = 4
	Op_Max         Op = 5
	Op_Mul         Op = 6
	Op_SetOnInsert Op = 7
)

var Op_name = map[int32]string{
	0: "Inc",
	1: "Set",
	2: "Unset",
	3: "CurrentDate",
	4: "Min",
	5: "Max",
	6: "Mul",
	7: "SetOnInsert",
}
var Op_value = map[string]int32{
	"Inc":         0,
	"Set":         1,
	"Unset":       2,
	"CurrentDate": 3,
	"Min":         4,
	"Max":         5,
	"Mul":         6,
	"SetOnInsert": 7,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}
func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{3}
}

type Value struct {
	Type                 Type     `protobuf:"varint,1,opt,name=type,proto3,enum=store.Type" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{0}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (dst *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(dst, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_Null
}

func (m *Value) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Entity struct {
	Data                 map[string]*Value `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{1}
}
func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (dst *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(dst, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetData() map[string]*Value {
	if m != nil {
		return m.Data
	}
	return nil
}

type Filter struct {
	Comp                 Comp     `protobuf:"varint,1,opt,name=Comp,proto3,enum=store.Comp" json:"Comp,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Value   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{2}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (dst *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(dst, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetComp() Comp {
	if m != nil {
		return m.Comp
	}
	return Comp_Eq
}

func (m *Filter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Filter) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Update struct {
	Op                   Op       `protobuf:"varint,1,opt,name=op,proto3,enum=store.Op" json:"op,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Value   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{3}
}
func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (dst *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(dst, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_Inc
}

func (m *Update) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Update) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{4}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Entity               *Entity  `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{5}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetResponse) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type PutRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Entity               *Entity  `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{6}
}
func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (dst *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(dst, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type PutResponse struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{7}
}
func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (dst *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(dst, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type ModifyRequest struct {
	Namespace            string    `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key                  string    `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Filters              []*Filter `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	Updates              []*Update `protobuf:"bytes,4,rep,name=updates,proto3" json:"updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ModifyRequest) Reset()         { *m = ModifyRequest{} }
func (m *ModifyRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyRequest) ProtoMessage()    {}
func (*ModifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{8}
}
func (m *ModifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyRequest.Unmarshal(m, b)
}
func (m *ModifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyRequest.Marshal(b, m, deterministic)
}
func (dst *ModifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyRequest.Merge(dst, src)
}
func (m *ModifyRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyRequest.Size(m)
}
func (m *ModifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyRequest proto.InternalMessageInfo

func (m *ModifyRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ModifyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ModifyRequest) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *ModifyRequest) GetUpdates() []*Update {
	if m != nil {
		return m.Updates
	}
	return nil
}

type ModifyResponse struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Successful           bool     `protobuf:"varint,3,opt,name=successful,proto3" json:"successful,omitempty"`
	Entity               *Entity  `protobuf:"bytes,4,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyResponse) Reset()         { *m = ModifyResponse{} }
func (m *ModifyResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyResponse) ProtoMessage()    {}
func (*ModifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{9}
}
func (m *ModifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyResponse.Unmarshal(m, b)
}
func (m *ModifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyResponse.Marshal(b, m, deterministic)
}
func (dst *ModifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyResponse.Merge(dst, src)
}
func (m *ModifyResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyResponse.Size(m)
}
func (m *ModifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyResponse proto.InternalMessageInfo

func (m *ModifyResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ModifyResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ModifyResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

func (m *ModifyResponse) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type DelRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelRequest) Reset()         { *m = DelRequest{} }
func (m *DelRequest) String() string { return proto.CompactTextString(m) }
func (*DelRequest) ProtoMessage()    {}
func (*DelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{10}
}
func (m *DelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelRequest.Unmarshal(m, b)
}
func (m *DelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelRequest.Marshal(b, m, deterministic)
}
func (dst *DelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelRequest.Merge(dst, src)
}
func (m *DelRequest) XXX_Size() int {
	return xxx_messageInfo_DelRequest.Size(m)
}
func (m *DelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelRequest proto.InternalMessageInfo

func (m *DelRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DelRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DelResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelResponse) Reset()         { *m = DelResponse{} }
func (m *DelResponse) String() string { return proto.CompactTextString(m) }
func (*DelResponse) ProtoMessage()    {}
func (*DelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{11}
}
func (m *DelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelResponse.Unmarshal(m, b)
}
func (m *DelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelResponse.Marshal(b, m, deterministic)
}
func (dst *DelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelResponse.Merge(dst, src)
}
func (m *DelResponse) XXX_Size() int {
	return xxx_messageInfo_DelResponse.Size(m)
}
func (m *DelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelResponse proto.InternalMessageInfo

type KeysRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeysRequest) Reset()         { *m = KeysRequest{} }
func (m *KeysRequest) String() string { return proto.CompactTextString(m) }
func (*KeysRequest) ProtoMessage()    {}
func (*KeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{12}
}
func (m *KeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysRequest.Unmarshal(m, b)
}
func (m *KeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysRequest.Marshal(b, m, deterministic)
}
func (dst *KeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysRequest.Merge(dst, src)
}
func (m *KeysRequest) XXX_Size() int {
	return xxx_messageInfo_KeysRequest.Size(m)
}
func (m *KeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeysRequest proto.InternalMessageInfo

type KeysResponse struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeysResponse) Reset()         { *m = KeysResponse{} }
func (m *KeysResponse) String() string { return proto.CompactTextString(m) }
func (*KeysResponse) ProtoMessage()    {}
func (*KeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{13}
}
func (m *KeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysResponse.Unmarshal(m, b)
}
func (m *KeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysResponse.Marshal(b, m, deterministic)
}
func (dst *KeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysResponse.Merge(dst, src)
}
func (m *KeysResponse) XXX_Size() int {
	return xxx_messageInfo_KeysResponse.Size(m)
}
func (m *KeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeysResponse proto.InternalMessageInfo

func (m *KeysResponse) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type CommandRequest struct {
	Command              Command        `protobuf:"varint,1,opt,name=command,proto3,enum=store.Command" json:"command,omitempty"`
	Get                  *GetRequest    `protobuf:"bytes,2,opt,name=get,proto3" json:"get,omitempty"`
	Put                  *PutRequest    `protobuf:"bytes,3,opt,name=put,proto3" json:"put,omitempty"`
	Modify               *ModifyRequest `protobuf:"bytes,4,opt,name=modify,proto3" json:"modify,omitempty"`
	Del                  *DelRequest    `protobuf:"bytes,5,opt,name=del,proto3" json:"del,omitempty"`
	Keys                 *KeysRequest   `protobuf:"bytes,6,opt,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{14}
}
func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (dst *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(dst, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

func (m *CommandRequest) GetCommand() Command {
	if m != nil {
		return m.Command
	}
	return Command_Get
}

func (m *CommandRequest) GetGet() *GetRequest {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *CommandRequest) GetPut() *PutRequest {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *CommandRequest) GetModify() *ModifyRequest {
	if m != nil {
		return m.Modify
	}
	return nil
}

func (m *CommandRequest) GetDel() *DelRequest {
	if m != nil {
		return m.Del
	}
	return nil
}

func (m *CommandRequest) GetKeys() *KeysRequest {
	if m != nil {
		return m.Keys
	}
	return nil
}

type CommandResponse struct {
	Command              Command         `protobuf:"varint,1,opt,name=command,proto3,enum=store.Command" json:"command,omitempty"`
	Get                  *GetResponse    `protobuf:"bytes,2,opt,name=get,proto3" json:"get,omitempty"`
	Put                  *PutResponse    `protobuf:"bytes,3,opt,name=put,proto3" json:"put,omitempty"`
	Modify               *ModifyResponse `protobuf:"bytes,4,opt,name=modify,proto3" json:"modify,omitempty"`
	Del                  *DelResponse    `protobuf:"bytes,5,opt,name=del,proto3" json:"del,omitempty"`
	Keys                 *KeysResponse   `protobuf:"bytes,6,opt,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommandResponse) Reset()         { *m = CommandResponse{} }
func (m *CommandResponse) String() string { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()    {}
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_store_ddfee7a2f29cd7da, []int{15}
}
func (m *CommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResponse.Unmarshal(m, b)
}
func (m *CommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResponse.Marshal(b, m, deterministic)
}
func (dst *CommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResponse.Merge(dst, src)
}
func (m *CommandResponse) XXX_Size() int {
	return xxx_messageInfo_CommandResponse.Size(m)
}
func (m *CommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResponse proto.InternalMessageInfo

func (m *CommandResponse) GetCommand() Command {
	if m != nil {
		return m.Command
	}
	return Command_Get
}

func (m *CommandResponse) GetGet() *GetResponse {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *CommandResponse) GetPut() *PutResponse {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *CommandResponse) GetModify() *ModifyResponse {
	if m != nil {
		return m.Modify
	}
	return nil
}

func (m *CommandResponse) GetDel() *DelResponse {
	if m != nil {
		return m.Del
	}
	return nil
}

func (m *CommandResponse) GetKeys() *KeysResponse {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "store.Value")
	proto.RegisterType((*Entity)(nil), "store.Entity")
	proto.RegisterMapType((map[string]*Value)(nil), "store.Entity.DataEntry")
	proto.RegisterType((*Filter)(nil), "store.Filter")
	proto.RegisterType((*Update)(nil), "store.Update")
	proto.RegisterType((*GetRequest)(nil), "store.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "store.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "store.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "store.PutResponse")
	proto.RegisterType((*ModifyRequest)(nil), "store.ModifyRequest")
	proto.RegisterType((*ModifyResponse)(nil), "store.ModifyResponse")
	proto.RegisterType((*DelRequest)(nil), "store.DelRequest")
	proto.RegisterType((*DelResponse)(nil), "store.DelResponse")
	proto.RegisterType((*KeysRequest)(nil), "store.KeysRequest")
	proto.RegisterType((*KeysResponse)(nil), "store.KeysResponse")
	proto.RegisterType((*CommandRequest)(nil), "store.CommandRequest")
	proto.RegisterType((*CommandResponse)(nil), "store.CommandResponse")
	proto.RegisterEnum("store.Command", Command_name, Command_value)
	proto.RegisterEnum("store.Type", Type_name, Type_value)
	proto.RegisterEnum("store.Comp", Comp_name, Comp_value)
	proto.RegisterEnum("store.Op", Op_name, Op_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KvsClient is the client API for Kvs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KvsClient interface {
	Command(ctx context.Context, opts ...grpc.CallOption) (Kvs_CommandClient, error)
}

type kvsClient struct {
	cc *grpc.ClientConn
}

func NewKvsClient(cc *grpc.ClientConn) KvsClient {
	return &kvsClient{cc}
}

func (c *kvsClient) Command(ctx context.Context, opts ...grpc.CallOption) (Kvs_CommandClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Kvs_serviceDesc.Streams[0], "/store.Kvs/Command", opts...)
	if err != nil {
		return nil, err
	}
	x := &kvsCommandClient{stream}
	return x, nil
}

type Kvs_CommandClient interface {
	Send(*CommandRequest) error
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type kvsCommandClient struct {
	grpc.ClientStream
}

func (x *kvsCommandClient) Send(m *CommandRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *kvsCommandClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KvsServer is the server API for Kvs service.
type KvsServer interface {
	Command(Kvs_CommandServer) error
}

func RegisterKvsServer(s *grpc.Server, srv KvsServer) {
	s.RegisterService(&_Kvs_serviceDesc, srv)
}

func _Kvs_Command_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KvsServer).Command(&kvsCommandServer{stream})
}

type Kvs_CommandServer interface {
	Send(*CommandResponse) error
	Recv() (*CommandRequest, error)
	grpc.ServerStream
}

type kvsCommandServer struct {
	grpc.ServerStream
}

func (x *kvsCommandServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *kvsCommandServer) Recv() (*CommandRequest, error) {
	m := new(CommandRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Kvs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "store.Kvs",
	HandlerType: (*KvsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Command",
			Handler:       _Kvs_Command_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "store.proto",
}

func init() { proto.RegisterFile("store.proto", fileDescriptor_store_ddfee7a2f29cd7da) }

var fileDescriptor_store_ddfee7a2f29cd7da = []byte{
	// 815 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdf, 0x6b, 0xe3, 0x46,
	0x10, 0x8e, 0x7e, 0x3a, 0x1e, 0x25, 0xce, 0x76, 0xdb, 0xb4, 0x6e, 0x28, 0x6d, 0x50, 0xd3, 0xc6,
	0xb8, 0x4d, 0x28, 0xee, 0x4b, 0x29, 0xa1, 0xd0, 0xc6, 0x8e, 0x09, 0xf9, 0xc9, 0xa6, 0x29, 0x94,
	0x42, 0x41, 0xb1, 0x37, 0xc1, 0x8d, 0x2c, 0x29, 0xda, 0x55, 0x88, 0xa0, 0xaf, 0xc7, 0x3d, 0xdf,
	0x5f, 0x7c, 0xc7, 0xec, 0xae, 0x62, 0xd9, 0x70, 0x47, 0xce, 0x4f, 0x1e, 0xcf, 0x7c, 0xfb, 0xcd,
	0x37, 0xdf, 0xce, 0x22, 0x08, 0x84, 0x4c, 0x73, 0xbe, 0x9f, 0xe5, 0xa9, 0x4c, 0xa9, 0xa7, 0xfe,
	0x84, 0x07, 0xe0, 0xfd, 0x15, 0xc5, 0x05, 0xa7, 0xdf, 0x80, 0x2b, 0xcb, 0x8c, 0xb7, 0xad, 0x6d,
	0xab, 0xd3, 0xea, 0x05, 0xfb, 0x1a, 0xfb, 0x67, 0x99, 0x71, 0xa6, 0x0a, 0x94, 0x82, 0x3b, 0x8e,
	0x64, 0xd4, 0xb6, 0xb7, 0xad, 0xce, 0x1a, 0x53, 0x71, 0xf8, 0x3f, 0xf8, 0x83, 0x44, 0x4e, 0x64,
	0x49, 0x7f, 0x30, 0x55, 0x6b, 0xdb, 0xe9, 0x04, 0xbd, 0x2f, 0xcc, 0x71, 0x5d, 0xdc, 0xef, 0x47,
	0x32, 0x1a, 0x24, 0x32, 0x2f, 0xf5, 0xb1, 0xad, 0x01, 0x34, 0x9f, 0x53, 0x94, 0x80, 0x73, 0xcf,
	0x4b, 0xd5, 0xb7, 0xc9, 0x30, 0xa4, 0x21, 0x78, 0x8f, 0xa8, 0x49, 0xb5, 0x0a, 0x7a, 0x6b, 0x86,
	0x4c, 0xe9, 0x64, 0xba, 0xf4, 0xab, 0xfd, 0x8b, 0x15, 0x46, 0xe0, 0x1f, 0x4d, 0x62, 0xc9, 0x73,
	0x14, 0x7f, 0x98, 0x4e, 0xb3, 0x05, 0xf1, 0x98, 0x62, 0xaa, 0x80, 0xe2, 0x93, 0x68, 0xaa, 0x19,
	0x9b, 0x4c, 0xc5, 0xb3, 0x36, 0xce, 0x7b, 0xdb, 0x84, 0xff, 0x80, 0x7f, 0x9d, 0x8d, 0x23, 0xc9,
	0xe9, 0x97, 0x60, 0xa7, 0x55, 0x83, 0xa6, 0x81, 0x5e, 0x64, 0xcc, 0x4e, 0x97, 0x27, 0x3f, 0x00,
	0x18, 0x72, 0xc9, 0xf8, 0x43, 0xc1, 0x85, 0xa4, 0x5f, 0x41, 0x13, 0x4f, 0x8a, 0x2c, 0x1a, 0x71,
	0xe3, 0xc6, 0x2c, 0x51, 0xb9, 0x64, 0x3f, 0xbb, 0x14, 0x8e, 0x21, 0x50, 0xa7, 0x45, 0x96, 0x26,
	0x82, 0x7f, 0xec, 0x71, 0xfa, 0x1d, 0xf8, 0x5c, 0xdd, 0x8e, 0x51, 0xb8, 0x3e, 0x77, 0x65, 0xcc,
	0x14, 0xc3, 0x11, 0xc0, 0x65, 0xb1, 0xac, 0xc6, 0x97, 0x36, 0xd9, 0x83, 0x40, 0x35, 0x31, 0xa3,
	0x7c, 0x0d, 0x20, 0x8a, 0xd1, 0x88, 0x0b, 0x71, 0x5b, 0xc4, 0xaa, 0xcd, 0x2a, 0xab, 0x65, 0xc2,
	0x37, 0x16, 0xac, 0x9f, 0xa5, 0xe3, 0xc9, 0x6d, 0xb9, 0xac, 0xae, 0x5d, 0x68, 0xdc, 0xaa, 0xcd,
	0x11, 0x6d, 0x47, 0x2d, 0x6c, 0x25, 0x4c, 0xef, 0x13, 0xab, 0xaa, 0x08, 0x2c, 0xd4, 0xfd, 0x8b,
	0xb6, 0x3b, 0x07, 0xd4, 0x5b, 0xc1, 0xaa, 0x6a, 0xf8, 0xda, 0x82, 0x56, 0xa5, 0x69, 0xc9, 0x1b,
	0x99, 0x1f, 0xdb, 0x59, 0x1c, 0xbb, 0x66, 0xa6, 0xfb, 0x21, 0x33, 0x0f, 0x00, 0xfa, 0x3c, 0x5e,
	0x76, 0xab, 0xd6, 0x21, 0x50, 0xa7, 0xf5, 0x0c, 0xf8, 0xf7, 0x84, 0x97, 0xc2, 0xb0, 0x85, 0x21,
	0xac, 0xe9, 0xbf, 0x66, 0x44, 0x0a, 0xee, 0x3d, 0x2f, 0x85, 0x7a, 0xf5, 0x4d, 0xa6, 0xe2, 0xf0,
	0xad, 0x05, 0xad, 0xc3, 0x74, 0x3a, 0x8d, 0x92, 0x71, 0x25, 0xa2, 0x03, 0x8d, 0x91, 0xce, 0x98,
	0x07, 0xd4, 0x9a, 0xbd, 0x50, 0x85, 0xab, 0xca, 0xf4, 0x5b, 0x70, 0xee, 0xb8, 0x34, 0x0f, 0xff,
	0x13, 0x83, 0x9a, 0x3d, 0x12, 0x86, 0x55, 0x04, 0x65, 0x85, 0x34, 0x2b, 0x55, 0x81, 0x66, 0x5b,
	0xca, 0xb0, 0x4a, 0x7f, 0x04, 0x7f, 0xaa, 0xee, 0xc3, 0xb8, 0xf5, 0x99, 0xc1, 0xcd, 0x2d, 0x0e,
	0x33, 0x18, 0xa4, 0x1c, 0xf3, 0xb8, 0xed, 0xcd, 0x51, 0xce, 0x6c, 0x64, 0x58, 0xa5, 0xdf, 0x9b,
	0x69, 0x7d, 0x85, 0xa2, 0x06, 0x55, 0xf3, 0xc7, 0x38, 0xf0, 0xca, 0x86, 0x8d, 0x67, 0x07, 0x8c,
	0x53, 0x2f, 0xb7, 0x60, 0xa7, 0x6e, 0x01, 0xad, 0x5b, 0xa0, 0xa9, 0xb4, 0x07, 0x3b, 0x75, 0x0f,
	0x68, 0xdd, 0x83, 0x0a, 0x85, 0x26, 0xec, 0x2d, 0x98, 0xb0, 0xb9, 0x60, 0x82, 0xc1, 0x56, 0x2e,
	0xec, 0xd4, 0x5d, 0xa0, 0x75, 0x17, 0x2a, 0x52, 0xb4, 0x61, 0x77, 0xce, 0x86, 0x4f, 0xe7, 0x6c,
	0x30, 0x38, 0x05, 0xe8, 0x0e, 0xa1, 0x61, 0xa6, 0xa3, 0x0d, 0x70, 0x86, 0x5c, 0x92, 0x15, 0x0c,
	0x2e, 0x0b, 0x49, 0x2c, 0x0a, 0xe0, 0x6b, 0x15, 0xc4, 0xc6, 0x64, 0x9f, 0xc7, 0xc4, 0xa1, 0x01,
	0x34, 0xfa, 0x3c, 0x8e, 0x7f, 0x8f, 0x63, 0xe2, 0xd2, 0x55, 0x70, 0x91, 0x94, 0x78, 0xdd, 0xbf,
	0xc1, 0xc5, 0x0f, 0x11, 0x66, 0xce, 0x8b, 0x38, 0xd6, 0x34, 0xc7, 0x09, 0xd2, 0x34, 0xc1, 0x3b,
	0x8a, 0xd3, 0x48, 0x12, 0x1b, 0xab, 0x7f, 0xa4, 0x29, 0xd2, 0x00, 0xf8, 0x57, 0x32, 0x9f, 0x24,
	0x77, 0x9a, 0xe5, 0x26, 0x4e, 0x6f, 0x88, 0x87, 0xd0, 0x28, 0xcf, 0xa3, 0x92, 0xf8, 0x98, 0xfc,
	0x4f, 0xa4, 0x09, 0x69, 0x74, 0xfb, 0xfa, 0xcb, 0x41, 0x7d, 0xb0, 0x07, 0x0f, 0x64, 0x05, 0x7f,
	0x87, 0xc8, 0x8b, 0x82, 0x25, 0x27, 0x36, 0x26, 0x4e, 0x25, 0x71, 0x30, 0x71, 0x2a, 0x39, 0x71,
	0x31, 0x71, 0xce, 0x89, 0x87, 0x4d, 0x06, 0x4f, 0x13, 0x21, 0x05, 0xf1, 0xbb, 0xff, 0x82, 0x7d,
	0x91, 0x69, 0x51, 0x23, 0xad, 0xee, 0x8a, 0x1b, 0x75, 0xd7, 0x89, 0xe0, 0xa8, 0x6e, 0x03, 0x82,
	0xc3, 0x22, 0xcf, 0x79, 0x22, 0xfb, 0x91, 0xe4, 0x9a, 0xf0, 0x6c, 0x92, 0x10, 0x57, 0x05, 0xd1,
	0x13, 0xf1, 0x54, 0x50, 0xc4, 0xc4, 0x47, 0xec, 0x15, 0x97, 0x17, 0xc9, 0x71, 0x22, 0x78, 0x2e,
	0x49, 0xa3, 0x37, 0x00, 0xe7, 0xe4, 0x51, 0xd0, 0xdf, 0x66, 0x86, 0x6e, 0x2e, 0xac, 0x8f, 0x5e,
	0xc0, 0xad, 0xcf, 0x17, 0xd3, 0xe6, 0x1d, 0xaf, 0x74, 0xac, 0x9f, 0xac, 0x1b, 0x5f, 0x7d, 0xfa,
	0x7f, 0x7e, 0x17, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x11, 0x03, 0x1e, 0x09, 0x08, 0x00, 0x00,
}
